application/leasing/forms.py
from flask_wtf import FlaskForm
from flask_wtf.html5 import NumberInput
from wtforms import IntegerField, SubmitField, HiddenField
from wtforms.validators import DataRequired
from flaskcarleasing.models import Contract


class ContractForm(FlaskForm):
    days_to_rent = IntegerField('Days to lease', validators=[DataRequired()], \
        widget=NumberInput(min=1, max=20))
    user = HiddenField()

    submit = SubmitField('Lease')

application/leasing/routes.py
from flask import render_template, Blueprint, abort, redirect, url_for, flash, request
from flask_login import login_required, current_user
from leasing.forms import ContractForm
from flaskcarleasing.models import Car, Contract
from flaskcarleasing.config import db
import datetime


leasing = Blueprint('leasing', __name__, template_folder='templates')


@leasing.route('/<int:car_id>', methods=['GET', 'POST'])
def index(car_id):
    if not current_user.is_authenticated:
        abort(401)

    car = Car.query.get_or_404(car_id)
    form = ContractForm()
    
    if form.validate_on_submit():
        days_to_rent = form.days_to_rent.data

        user_id = current_user.id
        lease_date = datetime.datetime.utcnow()
        return_date = lease_date + datetime.timedelta(days=days_to_rent)

        price = days_to_rent * car.price_per_day
        
        contract = Contract(user_id=user_id, car_id=car_id, lease_date=lease_date,\
            return_date=return_date, price=price)

        db.session.add(contract)
        db.session.commit()

        flash('Thank you for leasing our car. Our manager will call you back and then we deliver that car to you! Enjoy!')
        return redirect(url_for('main.index'))

    return render_template('leasing/index.html', car=car, form=form)


@leasing.route('/endcontract/<int:contract_id>', methods=['GET', 'POST'])
def end_contract(contract_id):
    if not current_user.is_authenticated:
        return abort(401)

    contract = Contract.query.get_or_404(contract_id)

    if contract.actual_return_date:
        return abort(403)

    actual_return_date = datetime.datetime.utcnow()

    penalty = 0

    if actual_return_date > contract.return_date:
        delta = (actual_return_date - contract.return_date).days
        penalty = contract.car.price_per_day * delta

    total_price = contract.price + penalty

    contract.actual_return_date = actual_return_date
    contract.total_price = total_price
    contract.penalty = penalty

    if request.method == 'POST':
        db.session.commit()

        flash(f'Contract {contract.id} was successfully ended! Thank you for using our services!')
        return redirect(url_for('main.index'))

    return render_template('leasing/end_contract.html', contract=contract)

application/leasing/templates/leasing/end_contract.html
{% extends "base.html" %}
{% block content %}

    <h2>End Contract {{ contract.id }}</h2>

    <div>
        <h3>Contract Info</h3>
        <hr>

        <p>
            Car: {{ contract.car.concern.title }} {{ contract.car.model }}
        </p>

        <p>
            Return date: {{ contract.return_date.strftime('%Y-%m-%d') }}
        </p>

        <p>
            Current date: {{ contract.actual_return_date.strftime('%Y-%m-%d') }}
        </p>

        <p>
            Outtime penalty: {{ contract.penalty }}
        </p>

        <p>
            Total price: ${{ contract.total_price }}
        </p>

        <form action="{{ url_for('leasing.end_contract', contract_id = contract.id) }}" method="POST">
            <input type="submit" value="End contract">
        </form>
    </div>
{% endblock content %}

application/leasing/templates/leasing/index.html
{% extends "base.html" %}
{% block content %}

    <h2>Lease that car?</h2>
    
    <div>
        <table>
            <tr>
                <td><img src="{{'/../static/pics/' + car.pic}}" alt=""></td>
                <td>
                    <div>
                        <h3>{{ car.concern.title }} {{ car.model }}</h3>

                        <hr>
                        <p>
                            {% if car.description %}
                                Description: {{ car.description }}
                            {% endif %}
                        </p>
                        <p> <b>Price: {{ car.price_per_day }} / day</b> </p>
                        <form action="{{ url_for('leasing.index', car_id=car.id) }}", method="POST">
                            {{ form.csrf_token }}
                            {{ form.days_to_rent.label }}:
                            {{ form.days_to_rent }}

                            {{ form.submit }}
                        </form>
                    </div>
                </td>
            </tr>
            <tr> 
            </tr>
        </table>
    </div>

{% endblock content %}