application/cars/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField, TextAreaField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired
from wtforms_sqlalchemy.fields import QuerySelectField
from flaskcarleasing.models import Concern


def get_concern_pk(obj):
    return str(obj)


class AddCarForm(FlaskForm):
    model = StringField('Model', validators=[DataRequired()])
    concern = QuerySelectField(u'Concern', query_factory=lambda: Concern.query, \
        allow_blank=False, get_label='title', get_pk=get_concern_pk)

    price_per_day = FloatField('Price per day', validators=[DataRequired()])
    description = TextAreaField('Description')

    pic = FileField('Load Picture', validators=[FileAllowed(['jpg', 'png'])])

    submit = SubmitField('Add')

application/cars/routes.py
from flask import render_template, redirect, url_for, request, Blueprint, abort
from flaskcarleasing.models import Car, Concern
from flaskcarleasing.config import db, delim, static_path
from cars.forms import AddCarForm
import hashlib
from flask import flash
from flask_login import current_user
import os
import secrets
from utils.functions import save_picture
from utils.decorators import check_rights


cars = Blueprint('cars', __name__, template_folder='templates')


@cars.route('/')
def index():
    page = request.args.get('page', 1, type=int)

    cs = Car.query.order_by(Car.id).paginate(page, 3, False)
    return render_template('cars/index.html', cars=cs)


@cars.route('/add', methods=['GET', 'POST'])
@check_rights
def add():
    print(current_user)

    form = AddCarForm()

    if form.validate_on_submit():
        car = Car()
        car.concern_id = form.concern.data.id
        car.model = form.model.data
        car.price_per_day = form.price_per_day.data
        car.description = form.description.data

        if form.pic.data:
            car.pic = save_picture(form.pic.data)
            
        db.session.add(car)
        db.session.commit()

        print(car.pic)

        flash(f'{car.concern.title} {car.model} was successfully added to db!', 'info')
        return redirect(url_for('cars.index'))

    return render_template('cars/add.html', form=form)

@cars.route('/<int:car_id>/update', methods=['GET', 'POST'])
@check_rights
def update(car_id):
    car = Car.query.get_or_404(car_id)
    form = AddCarForm()

    if request.method == 'GET':
        form.concern.data = car.concern
        form.price_per_day.data = car.price_per_day
        form.model.data = car.model
        form.submit.label.text = 'Edit'
        form.description.data = car.description

    if form.validate_on_submit():
        if form.pic.data and car.pic != 'default.png':
            pic_path = os.path.join(static_path, f'pics{delim}{car.pic}')
            os.remove(pic_path)

            car.pic = save_picture(form.pic.data)

        car.model = form.model.data
        car.concern = form.concern.data
        car.price_per_day = form.price_per_day.data
        car.description = form.description.data
        
        db.session.commit()
        db.session.flush()

        flash(f'Successfully edited {car.concern.title} {car.model}')
        return redirect(url_for('cars.update', car_id=car.id))

    return render_template('cars/update.html', car=car, form=form)


@cars.route('/<int:car_id>/delete', methods=['GET', 'POST'])
@check_rights
def delete(car_id):
    car = Car.query.get_or_404(car_id)

    if request.method == 'POST':
        db.session.delete(car)

        db.session.commit()
        db.session.flush()

        if car.pic != 'default.png':
            pic_path = os.path.join(static_path, f'pics{delim}{car.pic}')
            os.remove(pic_path)

        flash(f'{car.concern.title} {car.model} was removed from the database!')
        return redirect(url_for('concerns.view', title=car.concern.title))

    return render_template('cars/delete.html', car=car)  

application/cars/templates/cars/add.html
{% extends "base.html" %}
{% block content %}

    <form action="{{ url_for('cars.add') }}" method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}

        <p>
            {{ form.concern.label }}
            {{ form.concern }}
        </p>

        <p>
            {{ form.model.label }}
            {{ form.model(size=16) }}
        </p>

        <p>
            {{ form.description.label }}
            {{ form.description(rows='20', cols='70') }}
        </p>

        <p>
            {{ form.price_per_day.label }}
            {{ form.price_per_day(size=10) }}
        </p>

        <p>
            {{ form.pic.label }}
            {{ form.pic }}
            {% if form.pic.errors %}
                {% for error in form.pic.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.submit }}
        </p>
    </form>

{% endblock content %}

application/cars/templates/cars/delete.html
{% extends "base.html" %}
{% block content %}

    <h2>Are you sure you want to remove this car?</h2>

    <div>
        <table>
            <tr>
                <td><img src="{{'/../static/pics/' + car.pic}}" alt=""></td>
                <td>
                    <h3>{{ car.concern.title }} {{ car.model }}</h3>
                    <hr>
                    <p>Price: {{ car.price_per_day }}</p>
                    <form action="{{ url_for('cars.delete', car_id=car.id)}}" method="POST">
                        <input type="submit" value="Delete">
                    </form>
                </td>
            </tr>
            <tr> 
                
            </tr>
        </table>
    </div>

{% endblock content %}

application/cars/templates/cars/index.html
{% extends "base.html" %}
{% block content %}
    {% if current_user.superuser %}

        <a href="{{ url_for('cars.add') }}">Add Car</a>

    {% endif %}

    {% if cars %}
        {% for car in cars.items %}
        <div>
            <table>
                <tr>
                    <td><img src="{{'/../static/pics/' + car.pic}}" alt=""></td>
                    <td>
                        <div>
                            <h3>{{ car.concern.title }} {{ car.model }}</h3>

                            {% if current_user.superuser %}

                                <a href="{{ url_for('cars.update', car_id=car.id) }}">Update</a>
                                <a href="{{ url_for('cars.delete', car_id=car.id) }}">Delete</a>

                            {% endif %}

                            <hr>
                            <p>
                                {% if car.description %}
                                    Description: {{ car.description }}
                                {% endif %}
                            </p>
                            <p> <b>Price: ${{ car.price_per_day }} / day</b> </p>
                            <form action="{{ url_for('leasing.index', car_id=car.id) }}">
                                <input type="submit" value="Lease">
                            </form>
                        </div>
                    </td>
                </tr>
                <tr> 
                </tr>
            </table>
        </div>
        {% endfor %}
    {% else %}
        <h3>No Cars For Now</h3>
    {% endif %}

    {% for page_num in cars.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

        {% if page_num %}
            {% if cars.page == page_num %}
                <a>{{ page_num }}</a>
            {% else %}
                <a href="{{ url_for('cars.index', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}

    {% endfor %}

{% endblock content %}

application/cars/templates/cars/update.html
{% extends "base.html" %}
{% block content %}
    <table>
        <tr>
            <td><img src="{{'/../static/pics/' + car.pic}}" alt=""></td>
            <td>
                <form action="{{ url_for('cars.update', car_id=car.id) }}" method="POST" enctype="multipart/form-data">
                    {{ form.csrf_token }}
            
                    <p>
                        {{ form.concern.label }}
                        {{ form.concern }}
                    </p>
            
                    <p>
                        {{ form.model.label }}
                        {{ form.model(size=16) }}
                    </p>

                    <p>
                        {{ form.description.label }}
                        {{ form.description(rows='20', cols='70') }}
                    </p>
            
                    <p>
                        {{ form.price_per_day.label }}
                        {{ form.price_per_day(size=10) }}
                    </p>
            
                    <p>
                        {{ form.pic.label }}
                        {{ form.pic }}
                        {% if form.pic.errors %}
                            {% for error in form.pic.errors %}
                                {{ error }}
                            {% endfor %}
                        {% endif %}
                    </p>
            
                    <p>
                        {{ form.submit }}
                    </p>
                </form>
            </td>
        </tr>
        <tr> 
            
        </tr>
    </table>
{% endblock content %}