application/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, ValidationError
from wtforms.validators import DataRequired
from flaskcarleasing.models import User
from flask_login import current_user

class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired('This field is necessary!')])
    password = PasswordField('Password')

    first_name = StringField('First Name', validators=[DataRequired('This field is necessary!')])
    last_name = StringField('Last Name', validators=[DataRequired('This field is necessary!')])
    phone_number = StringField('Phone Number', validators=[DataRequired('This field is necessary!')])

    moderator_token = StringField('Moderator token')

    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()

        if user and user != current_user:
            raise ValidationError('User with such username already exists!')

    def validate_phone_number(self, phone_number):
        user = User.query.filter_by(phone_number=phone_number.data).first()

        if user and user != current_user:
            raise ValidationError('User with such phone number already exists!')


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember me')

    submit = SubmitField('Sign In')


class UpdateForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired('This field is necessary!')])
    password = PasswordField('Password')

    first_name = StringField('First Name', validators=[DataRequired('This field is necessary!')])
    last_name = StringField('Last Name', validators=[DataRequired('This field is necessary!')])
    phone_number = StringField('Phone Number', validators=[DataRequired('This field is necessary!')])

    submit = SubmitField('Sign Up')

application/users/routes.py
from flask import render_template, redirect, url_for, request, Blueprint, abort
from flaskcarleasing.models import Car, User
from flaskcarleasing.config import db, MODERATOR_TOKEN
from users.forms import RegisterForm, LoginForm, UpdateForm
import hashlib
from flask import flash
from flask_login import login_user, current_user, logout_user


users = Blueprint('users', __name__, template_folder='templates')


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash('You have already logged in')
        return redirect(url_for('main.index'))

    form = RegisterForm()
    
    if form.validate_on_submit():
        username = form.username.data

        password = form.password.data
        password = hashlib.md5(password.encode()).hexdigest()

        first_name = form.first_name.data
        last_name = form.last_name.data
        phone_number = form.phone_number.data

        user_info = {
            'username': username,
            'password': password,
            'first_name': first_name,
            'last_name': last_name,
            'phone_number': phone_number,
        }

        user = User(**user_info)
        
        db.session.add(user)
        db.session.commit()

        flash('You Now May Log In')

        return redirect(url_for('users.login'))
    return render_template('users/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    validation = None

    if current_user.is_authenticated:
        flash('You are logged in')
        return redirect(url_for('main.index'))

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        password = hashlib.md5(password.encode()).hexdigest()

        user = User.query.filter_by(username=username).first()

        if user and user.password == password:
            login_user(user, form.remember_me.data)
            flash('You Have Logged In')
            return redirect(url_for('main.index'))

    return render_template('users/login.html', form=form, validation=validation)


@users.route('/logout')
def logout():
    if not current_user.is_authenticated:
        abort(401)

    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
def account():
    if not current_user.is_authenticated:
        abort(401)

    form = RegisterForm()
    form.submit.label.text = 'Update user info'

    if request.method == 'GET':
        form.username.data = current_user.username
        form.phone_number.data = current_user.phone_number
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.phone_number = form.phone_number.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data

        if form.moderator_token.data == MODERATOR_TOKEN:
            current_user.superuser = True
            flash('Successfully activated moderator token. You now can create/update/delete items from the application database.')
            print(current_user)

        db.session.commit()

        flash('User info has been successfully changed')
        redirect(url_for('users.account'))

    return render_template('users/account.html', form=form)


@users.route('/contracts', methods=['GET', 'POSt'])
def contracts():
    if not current_user.is_authenticated:
        abort(401)

    user = current_user
    return render_template('users/contracts.html', user=user)

application/users/templates/users/account.html
{% extends "base.html" %}
{% block content %}
    <h2>User Info</h2>
    <a href="{{ url_for('users.contracts') }}">Check Contracts</a>
    <form action="{{ url_for('users.account') }}" method="POST">
        {{ form.csrf_token }}

        <p>
            {{ form.username.label }}
            {{ form.username(size=50) }}
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.password.label }}
            {{ form.password() }}
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.first_name.label }}
            {{ form.first_name(size=50) }}
            {% if form.first_name.errors %}
                {% for error in form.first_name.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.last_name.label }}
            {{ form.last_name(size=50) }}
        </p>

        <p>
            {{ form.phone_number.label }}
            {{ form.phone_number(size=20) }}

            {% if form.phone_number.errors %}
                {% for error in form.phone_number.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.moderator_token.label }}
            {{ form.moderator_token }}
        </p>

        {{ form.submit }}
    </form>
{% endblock content %}

application/users/templates/users/contracts.html
{% extends "base.html" %}
{% block content %}
    <h2>Your Contracts</h2>


    {% if user.contracts %}
        <table border="1">
            <tr>
                <td>First Name</td>
                <td>Last Name</td>
                <td>Phone Number</td>
                <td>Car</td>
                <td>Leasing Date</td>
                <td>Return Date</td>
                <td>Actual Return Date</td>
                <td>Price</td>
                <td>Outtime penalty</td>
                <td>Total Price</td>
                <td>Status</td>
                <td>
                    Fullfill
                </td>
            </tr>
            {% for contract in user.contracts %}
                <tr>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.phone_number }}</td>
                    <td>{{ contract.car.concern.title }} {{ contract.car.model }} </td>
                    <td>{{ contract.lease_date.strftime('%Y-%M-%d') }}</td>
                    <td>{{ contract.return_date.strftime('%Y-%M-%d') }}</td>
                    
                    <td>
                        {% if contract.actual_return_date %}
                            {{ contract.actual_return_date.strftime('%Y-%M-%d') }}
                        {% else %}
                            Not Returned
                        {% endif %}
                    </td>


                    <td>{{ contract.price }}</td>
                    <td>
                        {% if contract.penalty %}
                            ${{ contract.penalty }}
                        {% else %}
                            $0.0
                        {% endif %}
                    </td>

                    <td>
                        {% if contract.total_price %}
                            ${{ contract.total_price }}
                        {% else %}
                            Not Payed
                        {% endif %}
                    </td>

                    <td>
                        {% if contract.actual_return_date %}
                            Fullfilled
                        {% else %}
                            Active
                        {% endif %}
                    </td>

                    <td> 
                        <form action="{{ url_for('leasing.end_contract', contract_id=contract.id) }}">
                            {% if contract.actual_return_date %}
                                <input type="submit" value="Fulfilled" disabled>
                            {% else %}
                                <input type="submit" value="End Contract">
                            {% endif %}
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        You have no cars rented
    {% endif %}

{% endblock content %}

application/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
    <h2>Sign In</h2>

    <form action="{{ url_for('users.login') }}" method="POST">
        {{ form.csrf_token }}
        
        <p>
            {{ form.username.label }}
            {{ form.username }}
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.password.label }}
            {{ form.password }}
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.remember_me.label }}
            {{ form.remember_me }}
        </p>

        {{ form.submit }}

    </form>

{% endblock content %}

application/users/templates/users/register.html
{% extends "base.html" %}

{% block content %}
    <h2>Sign Up</h2>

    <form action="{{ url_for('users.register') }}" method="POST">
        {{ form.csrf_token }}

        <p>
            {{ form.username.label }}
            {{ form.username(size=50) }}
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.password.label }}
            {{ form.password() }}
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.first_name.label }}
            {{ form.first_name(size=50) }}
            {% if form.first_name.errors %}
                {% for error in form.first_name.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        <p>
            {{ form.last_name.label }}
            {{ form.last_name(size=50) }}
        </p>

        <p>
            {{ form.phone_number.label }}
            {{ form.phone_number(size=20) }}

            {% if form.phone_number.errors %}
                {% for error in form.phone_number.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}
        </p>

        {{ form.submit }}
    </form>
{% endblock content %}

{% block contracts %}
{% endblock contracts %}