application/concerns/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class AddConcernForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    submit = SubmitField('Add')

application/concerns/routes.py
from flask import render_template, redirect, url_for, request, Blueprint, abort
from flaskcarleasing.models import Concern, Car
from flaskcarleasing.config import db
from concerns.forms import AddConcernForm
from flask import flash
from flask_login import current_user
import os
from utils.decorators import check_rights

concerns = Blueprint('concerns', __name__, template_folder='templates')


@concerns.route('/')
def index():
    concerns = Concern.query.all()
    return render_template('concerns/index.html', concerns=concerns)


@concerns.route('/add', methods=['GET', 'POST'])
@check_rights
def add():
    print(current_user)

    if not current_user.superuser:
        abort(403)
    
    form = AddConcernForm()

    if form.validate_on_submit():
        title = form.title.data

        if Concern.query.filter_by(title=title).first():
            return redirect(url_for('concerns.add'))

        concern = Concern(title=title)
        db.session.add(concern)

        db.session.commit()
        return redirect(url_for('concerns.index'))

    return render_template('concerns/add.html', form=form)


@concerns.route('/<string:title>/update', methods=['GET', 'POST'])
@check_rights
def update(title):
    if not current_user.superuser:
        abort(403)

    concern = Concern.query.filter_by(title=title).first_or_404()
    form = AddConcernForm()

    if request.method == 'GET':
        form.title.data = concern.title
    form.submit.label.text = 'Update'

    if form.validate_on_submit():
        concern.title = form.title.data
        db.session.commit()

        return redirect(url_for('concerns.index'))

    return render_template('concerns/update.html', form=form, title=title)


@concerns.route('/<string:title>/cars')
def view(title):
    page = request.args.get('page', 1, type=int)
    concern = Concern.query.filter_by(title=title).first()

    cs = Car.query.filter_by(concern=concern).paginate(page, 3, False)
    return render_template('cars/index.html', cars=cs)

application/concerns/templates/concerns/add.html
{% extends "base.html" %}
{% block content %}

    <h2>Add Concern</h2>

    <form action="{{ url_for('concerns.add') }}" method="POST">
        {{ form.csrf_token }}

        <p>
            {{ form.title.label }}
            {{ form.title }}
        </p>

        {{ form.submit }}
    </form>

{% endblock content %}

application/concerns/templates/concerns/cars.html
{% extends "base.html" %}
{% block content %}
<h2>{{ concern_title }}</h2>
    {% for car in cars %}
        <div>
            <table>
                <tr>
                    <td><img src="{{'/../static/pics/' + car.pic}}" alt=""></td>
                    <td>
                        <h3>{{ car.concern.title }} {{ car.model }}</h3>

                        {% if current_user.superuser %}

                        <a href="{{ url_for('cars.update', car_id=car.id) }}">Update</a>
                        <a href="{{ url_for('cars.delete', car_id=car.id) }}">Delete</a>
                        {% endif %}

                        <!-- ADD ADMIN VALIDATION -->

                        <hr>
                        <p>
                            {% if car.description %}
                                Description: {{ car.description }}
                            {% endif %}
                        </p>
                        <p> <b>Price: {{ car.price_per_day }} / day</b> </p>
                        <form action="#">
                            <input type="submit" value="Lease">
                        </form>
                    </td>
                </tr>
                <tr> 
                    
                </tr>
            </table>
        </div>
    {% endfor %}

{% endblock content %}

application/concerns/templates/concerns/index.html
{% extends "base.html" %}
{% block content %}

    {% if current_user.superuser %}
        <a href="{{ url_for('concerns.add') }}">Add Concern</a>
    {% endif %}

    <h2>Concerns</h2>

    {% if concerns %}
        {% for concern in concerns %}

            
            <p>
                <a href="{{ url_for('concerns.view', title=concern.title) }}">{{ concern.title }}</a>
                
                {% if current_user.superuser %}
                    <a href="{{ url_for('concerns.update', title=concern.title) }}">Update</a>
                {% endif %}
            </p>
        {% endfor %}
    {% else %}
        <h3>No Cars For Now</h3>
    {% endif %}

{% endblock content %}

application/concerns/templates/concerns/update.html
{% extends "base.html" %}

{% block content %}

    <h2>Edit Concern</h2>

    <form action="{{ url_for('concerns.update', title=title) }}" method="POST">
        {{ form.csrf_token }}

        <p>
            {{ form.title.label }}
            {{ form.title }}
        </p>

        {{ form.submit }}
    </form>

{% endblock content %}